### ISSUE TITLE
Fix vulnerable dependencies in Gemfile

### ISSUE THREAD

**Issue by vcavallo** [vcavallo/impostor_roster#9]
see: https://github.com/vcavallo/impostor_roster/network/dependencies

**Comment by muhtarudinsiregar** [comment]
Hi @vcavallo, i think can help you to elaborate with this issue. So, i research a bit about this issue, maybe this is what you want? 
https://medium.com/cedarcode/reduce-fear-of-bundle-update-with-this-4-step-process-e021e8808c48

**Comment by asarbu** [comment]
@vcavallo I searched for vulnerabilities. Have a look on my PR and let me know what you think

**Comment by thovt93** [comment]
I will take this
